# Generated by Django 4.2.16 on 2024-11-05 00:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_book_fecha_creacion_book_fecha_modificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 4, 21, 3, 52, 265057)),
        ),
        migrations.AlterField(
            model_name='book',
            name='fecha_modificacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 4, 21, 3, 52, 265074)),
        ),
    ]
